# Generated by Django 5.1.4 on 2025-02-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokenSecret', models.CharField(max_length=32)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
